import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Polybase } from "@polybase/client";

const db = new Polybase({
  defaultNamespace:
    "pk/0xf699df4b2989f26513d93e14fd6e0befd620460546f3706a4e35b10ac3838457a031504254ddac46f6519fcf548ec892cc33043ce74c5fa9018ef5948a685e1d/splitonchain",
});
const collectionReference = db.collection("City");

export default function Home() {
  async function createRecord() {
    // .create(args) args array is defined by the constructor fn
    try {
      console.log("creating entry");
      const recordData = await collectionReference.create([
        "test2",
        "New York",
      ]);
      console.log("record created", recordData);
    } catch (error) {
      console.log("error while creating city", error);
    }
  }
  async function getRecord() {
    const { data, block } = await collectionReference.record("test2").get();
    console.log("fecthed ", data, block);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>SplitOnChain</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <h1 className={styles.title}>Welcome to SplitOnChain</h1>

      <div className={styles.grid}>
        <div className={styles.card}>
          <h2>Create City &rarr;</h2>
          <button onClick={createRecord}>Create</button>
        </div>
        <div className={styles.card}>
          <h2>Read City &rarr;</h2>
          <button onClick={getRecord}>Read</button>
        </div>
      </div>
    </div>
  );
}
